name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at interval of every 2 hr
    - cron: '* */2 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_LINES_OF_CODE: 'True'
          SHOW_TIMEZONE: 'False'
          SHOW_OS: 'False'
          SHOW_LOC_CHART: 'False'
          LOCALE: 'en'
